//alignas
// alignof
// and
// and_eq
// asm; used to insert assembly language commands directly into the code 
// auto used to declare local variables but its purely optional 
// bitand
// bitor
// bool 1 byte used to declare a boolean logic variable true or false 
// break used to break out of loop independant of the loop condition 
// case used as a label to declare a single test in a switch statement 
// catch used to handle exceptions generated by a throw statement 
// char a byte long used to declare character vars 
// char8_t (since C++20)
// char16_t
// char32_t
// class used to define new class, memebers are private by default unless listed under protected or public labels 
// compl
// concept (since C++20)
// const used to tell the compiler that a certain object should not be modified once it has been initialized 
// consteval (since C++20)
// constexpr
// constinit (since C++20)
// const_cast
// continue
// co_await (since C++20)
// co_return (since C++20)
// co_yield (since C++20)
// decltype
// default
// delete

// do
// double
// dynamic_cast
// else
// enum
// explicit
// export
// extern
// false
// float
// for
// friend
// goto
// if
// inline
// int
// long
// mutable
// namespace
// new
// noexcept
// not
// not_eq
// nullptr
// operator
// or
// or_eq
// private
// protected
// public
// register

// reinterpret_cast
// requires (since C++20)
// return
// short
// signed
// sizeof
// static
// static_assert
// static_cast
// struct
// switch
// template
// this
// thread_local
// throw
// true
// try
// typedef
// typeid
// typename
// union
// unsigned
// using
// virtual
// void
// volatile
// wchar_t
// while
// xor
// xor_eq